### ISSUE TITLE
custom folders are empty and Signal status area is empty

### ISSUE THREAD

**Issue by auscon22** [doubleohwhatever/goes-tools-panel#1]
I followed all the steps to setup. But the custom folders are empty they are there. Also, Signal status area is empty. I don't know what I doing wrong. Every thing else is working fine. I love the project it was just what I was looking for!

**Comment by ghost** [comment]
I'm afraid this project is pretty much abandoned at the moment because I no longer have my receiving running. When/If I set it up again, I'll be sure to update this project.

**Comment by auscon22** [comment]
Okay Thanks!
